config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    # Root
    root "home#index"

    # Authentication
    devise_for :users

    # Resources
    resources :offices do
      resources :comments, only: [:create, :destroy]
      get "/report(/:year(/:month(/:day)))(.:format)" => "report#report", as: :report
      post "/report" => "report#redirect_report", as: :redirect_report
    end
    resources :shifts
    resources :vacations
    resources :workers do
      resources :comments, only: [:create, :destroy]
      get "/report(/:year(/:month(/:day)))(.:format)" => "report#report", as: :report
      post "/report" => "report#redirect_report", as: :redirect_report
    end

    # Dashboard
    get "/dashboard" => "dashboard#index"

    # Terminal
    get "/terminal/:id" => "terminal#office", as: :terminal_office
    post "/terminal/:id" => "terminal#check", as: :terminal_office_check

    # Admin
    namespace :admin do
      resources :shift_corrections, only: [:index]
      get "/shift_corrections/edit_shift/:id" => "shift_corrections#edit_shift", as: :edit_shift
      patch "/shift_corrections/update_shift/:id" => "shift_corrections#update_shift", as: :update_shift
    end
  end
end

app/models/office.rb
class Office < ApplicationRecord

  validates :name, presence: true, uniqueness: true

  has_many :workers, dependent: :nullify
  has_many :shifts, dependent: :nullify
  has_many :comments, as: :commentable

  def full_address
    [address_1, address_2, postcode, city, country].compact.join(', ')
  end

end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  include Pagination

  before_action :set_office, only: %i[ show edit update destroy ]

  # GET /offices or /offices.json
  def index
    authorize! :read, Office
    @offices = paginate Office
  end

  # GET /offices/1 or /offices/1.json
  def show
    authorize! :show, @office
  end

  # GET /offices/new
  def new
    authorize! :create, Office
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
    authorize! :update, @office
  end

  # POST /offices or /offices.json
  def create
    authorize! :create, Office
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to office_url(@office), success: t("crud.controller.success.created", name: @office.name) }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1 or /offices/1.json
  def update
    authorize! :update, @office

    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to office_url(@office), success: t("crud.controller.success.edited", name: @office.name) }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1 or /offices/1.json
  def destroy
    authorize! :destroy, @office
    @office.destroy

    respond_to do |format|
      format.html { redirect_to offices_url, notice: t("crud.controller.success.deleted", name: @office.name) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def office_params
      params.require(:office).permit(:name, :description, :address_1, :address_2, :postcode, :city, :country)
    end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.slim
= simple_form_for(@office) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :address_1
    = f.input :address_2
    = f.input :postcode
    = f.input :city
    = f.input :country

  .form-actions
    = f.button :submit, class: "btn-primary"

app/views/offices/edit.html.slim
= page_heading t("office.titles.edit_html", name: @office.name)

== render "form", office: @office

br

div
  => link_to t("office.links.view"), @office
  '|
  =< link_to t("office.links.back_list"), offices_path

app/views/offices/index.html.slim
= page_heading t("office.titles.list")

- if can? :create, Office
  h1
    a< class="text-black" href=new_office_path
      i class="bi bi-plus-square-fill"

div class="table-responsive"
  table class="table table-striped table-sm records-table"
    thead class="table-dark"
      tr
        th
          a class=(@pager.sort_by == "id" ? "fst-italic" : "") href=offices_path(sort_by: "id", sort_order: (@pager.sort_order == "asc" ? :desc : :asc))
            = t("id")
          - if @pager.sort_by == "id"
            - if @pager.sort_order == "asc"
              i<> class="bi bi-caret-up-fill"
            - else
              i<> class="bi bi-caret-down-fill"
        th
          a class=(@pager.sort_by == "name" ? "fst-italic" : "") href=offices_path(sort_by: "name", sort_order: (@pager.sort_order == "asc" ? :desc : :asc))
            = Office.human_attribute_name :name
          - if @pager.sort_by == "name"
            - if @pager.sort_order == "asc"
              i<> class="bi bi-caret-up-fill"
            - else
              i<> class="bi bi-caret-down-fill"
        th
          a class=(@pager.sort_by == "description" ? "fst-italic" : "") href=offices_path(sort_by: "description", sort_order: (@pager.sort_order == "asc" ? :desc : :asc))
            = Office.human_attribute_name :description
          - if @pager.sort_by == "description"
            - if @pager.sort_order == "asc"
              i<> class="bi bi-caret-up-fill"
            - else
              i<> class="bi bi-caret-down-fill"
        th = Office.human_attribute_name :full_address
        th = Office.human_attribute_name :workers
        th = t("actions.actions")
    tbody class="table-group-divider"
      - @offices.each do |office|
        tr
          th = office.id
          td
            a href=office_path(office) = office.name
          td = office.description
          td = office.full_address
          td = office.workers.size
          td
            - if can? :terminal, office
              button type="button" class="btn btn-primary btn-sm me-2"
                a class="text-white" href=terminal_office_path(office)
                  = t("office.terminal.button")
                  i class="bi bi-box-arrow-right ps-2"
            - if can? :edit, office
              button type="button" class="btn btn-primary btn-sm me-2"
                a class="text-white" href=edit_office_path(office)
                  = t("actions.edit")
                  i class="bi bi-pencil-fill ps-2"
            - if can? :destroy, office
              button type="button" class="btn btn-primary btn-sm me-2"
                a class="text-white" href=office_path(office) data-method="delete" data-confirm=t("actions.confirm")
                  = t("actions.delete")
                  i class="bi bi-trash-fill ps-2"

= pagination

app/views/offices/new.html.slim
= page_heading t("office.titles.create")

== render "form", office: @office

br

div
  = link_to t("office.links.back_list"), offices_path

app/views/offices/show.html.slim
div class="container bg-light rounded-3 p-5 mb-4"
  div class="d-flex"
    div class="flex-grow-1 ms-3"
      = page_heading @office.name

      div class="row"
        div class="col-4"
          = Office.human_attribute_name :description
        div class="col-8"
          - if @office.description.present?
            = @office.description

      div class="row"
        div class="col-4"
          = Office.human_attribute_name :full_address
        div class="col-8"
          = @office.full_address

      div class="row"
        div class="col-4"
          = Office.human_attribute_name :workers
        div class="col-8"
          = @office.workers.size

    div class="flex-shrink-0"

  div class="container-fluid mt-3"
    div class="row"
      div class="col-12"
        - if can? :terminal, @office
          button type="button" class="btn btn-dark btn-lg me-2"
            a class="text-white" href=terminal_office_path(@office)
              = t("office.terminal.button")
              i class="bi bi-box-arrow-right ps-2"
        - if can? :read, @office.shifts
          div class="btn-group me-2"
            button type="button" class="btn btn-dark btn-lg "
              a class="text-white" href=office_report_path(@office)
                = t("report.button")
                i class="bi bi-graph-up ps-2"
            button class="btn btn-dark dropdown-toggle dropdown-toggle-split" type="button" data-bs-toggle="dropdown" aria-expanded="false"
            ul class="dropdown-menu"
              li
                a class="dropdown-item" href=office_report_path(@office, year: Date.today.year) = t("report.yearly")
              li
                a class="dropdown-item" href=office_report_path(@office, year: Date.today.year, month: Date.today.month) = t("report.monthly")
              li
                a class="dropdown-item" href=office_report_path(@office, year: Date.today.year, month: Date.today.month, day: Date.today.day) = t("report.daily")
        - if can? :update, @office
          button type="button" class="btn btn-dark btn-lg me-2"
            a class="text-white" href=edit_office_path(@office)
              = t("actions.edit")
              i class="bi bi-pencil-fill ps-2"
        - if can? :destroy, @office
          button type="button" class="btn btn-danger btn-lg me-2"
            a class="text-white" href=office_path(@office) data-method="delete" data-confirm=t("actions.confirm")
              = t("actions.delete")
              i class="bi bi-trash-fill ps-2"

  div class="container-fluid mt-3"
    = render "comments/list", entity: @office, entity_id: @office.id, entity_class: @office.class