config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    # Root
    root "home#index"

    # Authentication
    devise_for :users

    # Resources
    resources :offices do
      resources :comments, only: [:create, :destroy]
      get "/report(/:year(/:month(/:day)))(.:format)" => "report#report", as: :report
      post "/report" => "report#redirect_report", as: :redirect_report
    end
    resources :shifts
    resources :vacations
    resources :workers do
      resources :comments, only: [:create, :destroy]
      get "/report(/:year(/:month(/:day)))(.:format)" => "report#report", as: :report
      post "/report" => "report#redirect_report", as: :redirect_report
    end

    # Dashboard
    get "/dashboard" => "dashboard#index"

    # Terminal
    get "/terminal/:id" => "terminal#office", as: :terminal_office
    post "/terminal/:id" => "terminal#check", as: :terminal_office_check

    # Admin
    namespace :admin do
      resources :shift_corrections, only: [:index]
      get "/shift_corrections/edit_shift/:id" => "shift_corrections#edit_shift", as: :edit_shift
      patch "/shift_corrections/update_shift/:id" => "shift_corrections#update_shift", as: :update_shift
    end
  end
end

app/models/vacation.rb
class Vacation < ApplicationRecord

  validates :worker_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  belongs_to :worker

  def duration
    (self.end_date - self.start_date).to_int
  end

end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  include Pagination

  before_action :set_vacation, only: %i[ show edit update destroy ]

  # GET /vacations or /vacations.json
  def index
    authorize! :read, Vacation
    @vacations = paginate Vacation, :start_date, :desc
  end

  # GET /vacations/1 or /vacations/1.json
  def show
    authorize! :show, @vacation
  end

  # GET /vacations/new
  def new
    authorize! :create, Vacation
    @vacation = Vacation.new
  end

  # GET /vacations/1/edit
  def edit
    authorize! :update, @vacation
  end

  # POST /vacations or /vacations.json
  def create
    authorize! :create, Vacation
    @vacation = Vacation.new(vacation_params)

    respond_to do |format|
      if @vacation.save
        format.html { redirect_to vacation_url(@vacation), success: t("crud.controller.success.created", name: Vacation.model_name.human) }
        format.json { render :show, status: :created, location: @vacation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacations/1 or /vacations/1.json
  def update
    authorize! :update, @vacation

    respond_to do |format|
      if @vacation.update(vacation_params)
        format.html { redirect_to vacation_url(@vacation), success: t("crud.controller.success.edited", name: Vacation.model_name.human) }
        format.json { render :show, status: :ok, location: @vacation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacations/1 or /vacations/1.json
  def destroy
    authorize! :destroy, @vacation
    @vacation.destroy

    respond_to do |format|
      format.html { redirect_to vacations_url, notice: t("crud.controller.success.deleted", name: Vacation.model_name.human) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacation
      @vacation = Vacation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vacation_params
      params.require(:vacation).permit(:start_date, :end_date, :worker_id)
    end
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/views/vacations/_form.html.slim
= simple_form_for(@vacation) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :start_date
    = f.input :end_date
    = f.association :worker

  .form-actions
    = f.button :submit, class: "btn-primary"

app/views/vacations/edit.html.slim
= page_heading t("vacation.titles.edit_html", id: @vacation.id)

== render "form", vacation: @vacation

br

div
  => link_to t("vacation.links.view"), @vacation
  '|
  =< link_to t("vacation.links.back_list"), vacations_path

app/views/vacations/index.html.slim
= page_heading t("vacation.titles.list")

- if can? :create, Vacation
  h1
    a< class="text-black" href=new_vacation_path
      i class="bi bi-plus-square-fill"

div class="table-responsive"
  table class="table table-striped table-sm records-table"
    thead class="table-dark"
      tr
        th
          a class=(@pager.sort_by == "id" ? "fst-italic" : "") href=vacations_path(sort_by: "id", sort_order: (@pager.sort_order == "asc" ? :desc : :asc))
            = t("id")
          - if @pager.sort_by == "id"
            - if @pager.sort_order == "asc"
              i<> class="bi bi-caret-up-fill"
            - else
              i<> class="bi bi-caret-down-fill"

        th = Vacation.human_attribute_name :worker
        th
          a class=(@pager.sort_by == "start_date" ? "fst-italic" : "") href=vacations_path(sort_by: "start_date", sort_order: (@pager.sort_order == "asc" ? :desc : :asc))
            = Vacation.human_attribute_name :start_date
          - if @pager.sort_by == "start_date"
            - if @pager.sort_order == "asc"
              i<> class="bi bi-caret-up-fill"
            - else
              i<> class="bi bi-caret-down-fill"
        th
          a class=(@pager.sort_by == "end_date" ? "fst-italic" : "") href=vacations_path(sort_by: "end_date", sort_order: (@pager.sort_order == "asc" ? :desc : :asc))
            = Vacation.human_attribute_name :end_date
          - if @pager.sort_by == "end_date"
            - if @pager.sort_order == "asc"
              i<> class="bi bi-caret-up-fill"
            - else
              i<> class="bi bi-caret-down-fill"
        th = Vacation.human_attribute_name :duration
        th = t("actions.actions")
    tbody class="table-group-divider"
      - @vacations.each do |vacation|
        tr
          th = vacation.id
          td
            a href=worker_path(vacation.worker) = vacation.worker.name
          td = l(vacation.start_date, :format => :long)
          td = l(vacation.end_date, :format => :long)
          td = t("duration.days", days: vacation.duration)
          td
            button type="button" class="btn btn-primary btn-sm me-2"
              a class="text-white" href=vacation_path(vacation)
                = t("actions.view")
                i class="bi bi-eye-fill ps-2"
            - if can? :update, vacation
              button type="button" class="btn btn-primary btn-sm me-2"
                a class="text-white" href=edit_vacation_path(vacation)
                  = t("actions.edit")
                  i class="bi bi-pencil-fill ps-2"
            - if can? :destroy, vacation
              button type="button" class="btn btn-primary btn-sm me-2"
                a class="text-white" href=vacation_path(vacation) data-method="delete" data-confirm=t("actions.confirm")
                  = t("actions.delete")
                  i class="bi bi-trash-fill ps-2"

= pagination

app/views/vacations/new.html.slim
= page_heading t("vacation.titles.create")

== render "form", vacation: @vacation

br

div
  = link_to t("vacation.links.back_list"), vacations_path

app/views/vacations/show.html.slim
div class="container bg-light rounded-3 p-5 mb-4"
  div class="d-flex"
    div class="flex-grow-1 ms-3"
      = page_heading @vacation.worker.name

      div class="row"
        div class="col-4"
          = Vacation.human_attribute_name :start_date
        div class="col-8"
          - if @vacation.start_date.present?
            = l(@vacation.start_date, :format => :long)

      div class="row"
        div class="col-4"
          = Vacation.human_attribute_name :end_date
        div class="col-8"
          - if @vacation.end_date.present?
            = l(@vacation.end_date, :format => :long)

      div class="row"
        div class="col-4"
          = Vacation.human_attribute_name :duration
        div class="col-8"
          = t("duration.days", days: @vacation.duration)

    div class="flex-shrink-0"

  div class="container-fluid mt-3"
    div class="row"
      div class="col-12"
        - if can? :update, @vacation
          button type="button" class="btn btn-dark btn-lg me-2"
            a class="text-white" href=edit_vacation_path(@vacation)
              = t("actions.edit")
              i class="bi bi-pencil-fill ps-2"
        - if can? :destroy, @vacation
          button type="button" class="btn btn-danger btn-lg me-2"
            a class="text-white" href=vacation_path(@vacation) data-method="delete" data-confirm=t("actions.confirm")
              = t("actions.delete")
              i class="bi bi-trash-fill ps-2"