config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    # Root
    root "home#index"

    # Authentication
    devise_for :users

    # Resources
    resources :offices do
      resources :comments, only: [:create, :destroy]
      get "/report(/:year(/:month(/:day)))(.:format)" => "report#report", as: :report
      post "/report" => "report#redirect_report", as: :redirect_report
    end
    resources :shifts
    resources :vacations
    resources :workers do
      resources :comments, only: [:create, :destroy]
      get "/report(/:year(/:month(/:day)))(.:format)" => "report#report", as: :report
      post "/report" => "report#redirect_report", as: :redirect_report
    end

    # Dashboard
    get "/dashboard" => "dashboard#index"

    # Terminal
    get "/terminal/:id" => "terminal#office", as: :terminal_office
    post "/terminal/:id" => "terminal#check", as: :terminal_office_check

    # Admin
    namespace :admin do
      resources :shift_corrections, only: [:index]
      get "/shift_corrections/edit_shift/:id" => "shift_corrections#edit_shift", as: :edit_shift
      patch "/shift_corrections/update_shift/:id" => "shift_corrections#update_shift", as: :update_shift
    end
  end
end

app/models/admin/shift_correction.rb
class Admin::ShiftCorrection < ApplicationRecord

  validates :editor, presence: true
  validates :description, presence: true

  belongs_to :shift, optional: false

end

app/controllers/admin/shift_corrections_controller.rb
class Admin::ShiftCorrectionsController < ApplicationController
  include Pagination

  before_action :set_shift, only: %i[ edit_shift update_shift ]

  # GET /admin/shift_corrections or /admin/shift_corrections.json
  def index
    authorize! :read, Admin::ShiftCorrection
    @shift_corrections = paginate Admin::ShiftCorrection, :id, :asc
  end

  # GET /admin/shift_corrections/edit_shift/1
  def edit_shift
    authorize! :update, @shift
  end

  # POST /admin/shift_corrections/update_shift/1
  def update_shift
    authorize! :update, @shift
    @shift.update!(shift_params)
    correction = Admin::ShiftCorrection.new(correction_params.merge(shift: @shift))
    correction.save!
    redirect_to shift_url(@shift), success: t("crud.controller.success.edited", name: @shift.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    def shift_params
      params.require(:shift).permit(:start_time, :end_time)
    end

  def correction_params
    params.require(:correction).permit(:editor, :description)
  end

end

app/helpers/admin/shift_corrections_helper.rb
module Admin::ShiftCorrectionsHelper
end

app/views/admin/shift_corrections/_list.html.slim
- corrections = @shift.corrections.order(created_at: :desc)

- if corrections.any?
  div class="correction-section border-top pt-3"
    div class="row"
      div class="col-12"
        h5
          = Admin::ShiftCorrection.model_name.human(count: corrections.count)
          span<> class="badge bg-primary" = corrections.count

      div class="col-12"
        - corrections.each do |correction|
          div class="card mb-3"
            div class="card-body"
              p class="card-text" = correction.description
              span<> class="float-end"
                = correction.editor
                |  -
                span<> class="date" data-date=l(correction.created_at) = format_time(correction.created_at)

app/views/admin/shift_corrections/edit_shift.html.slim
= page_heading t("shift_correction.titles.edit_shift_html", id: @shift.id)

= simple_form_for(@shift, url: admin_update_shift_path(id: @shift.id)) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :start_time
    = f.input :end_time
    = simple_fields_for :correction do |c|
      = c.hidden_field :editor, value: current_user.username
      = c.input :description, as: :text, required: true

  .form-actions
    = f.button :submit, class: "btn-primary"

app/views/admin/shift_corrections/index.html.slim
= page_heading t("shift_correction.titles.list")

div class="table-responsive"
  table class="table table-striped table-sm records-table"
    thead class="table-dark"
      tr
        th
          a class=(@pager.sort_by == "id" ? "fst-italic" : "") href=admin_shift_corrections_path(sort_by: "id", sort_order: (@pager.sort_order == "asc" ? :desc : :asc))
            = t("id")
          - if @pager.sort_by == "id"
            - if @pager.sort_order == "asc"
              i<> class="bi bi-caret-up-fill"
            - else
              i<> class="bi bi-caret-down-fill"

        th = Admin::ShiftCorrection.human_attribute_name :editor
        th = Admin::ShiftCorrection.human_attribute_name :description
        th = Admin::ShiftCorrection.human_attribute_name :shift
        th = Admin::ShiftCorrection.human_attribute_name :created_at
    tbody class="table-group-divider"
      - @shift_corrections.each do |correction|
        tr
          th = correction.id
          td = correction.editor
          td = correction.description
          td
            a href=shift_path(correction.shift) = correction.shift.id
          td = correction.created_at

= pagination