config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    # Root
    root "home#index"

    # Authentication
    devise_for :users

    # Resources
    resources :offices do
      resources :comments, only: [:create, :destroy]
      get "/report(/:year(/:month(/:day)))(.:format)" => "report#report", as: :report
      post "/report" => "report#redirect_report", as: :redirect_report
    end
    resources :shifts
    resources :vacations
    resources :workers do
      resources :comments, only: [:create, :destroy]
      get "/report(/:year(/:month(/:day)))(.:format)" => "report#report", as: :report
      post "/report" => "report#redirect_report", as: :redirect_report
    end

    # Dashboard
    get "/dashboard" => "dashboard#index"

    # Terminal
    get "/terminal/:id" => "terminal#office", as: :terminal_office
    post "/terminal/:id" => "terminal#check", as: :terminal_office_check

    # Admin
    namespace :admin do
      resources :shift_corrections, only: [:index]
      get "/shift_corrections/edit_shift/:id" => "shift_corrections#edit_shift", as: :edit_shift
      patch "/shift_corrections/update_shift/:id" => "shift_corrections#update_shift", as: :update_shift
    end
  end
end

app/models/shift.rb
class Shift < ApplicationRecord

  validates :worker_id, presence: true
  validates :start_time, presence: true

  belongs_to :worker
  belongs_to :office

  has_many :corrections, :class_name => 'Admin::ShiftCorrection', dependent: :nullify

  def date
    self.start_time.to_date
  end

  def duration
    if self.end_time.present?
      time_diff = (self.end_time - self.start_time)
      (time_diff / 1.minute).round(1)
    end
  end

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  include Pagination

  before_action :set_shift, only: %i[ show edit update destroy ]

  # GET /shifts or /shifts.json
  def index
    authorize! :read, Shift
    @shifts = paginate Shift, :start_time, :desc
  end

  # GET /shifts/1 or /shifts/1.json
  def show
    authorize! :show, @shift
  end

  # GET /shifts/new
  def new
    authorize! :create, Shift
    @shift = Shift.new
  end

  # GET /shifts/1/edit
  def edit
    authorize! :update, @shift
  end

  # POST /shifts or /shifts.json
  def create
    authorize! :create, Shift
    @shift = Shift.new(shift_params)

    respond_to do |format|
      if @shift.save
        format.html { redirect_to shift_url(@shift), success: t("crud.controller.success.created", name: Shift.model_name.human) }
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shifts/1 or /shifts/1.json
  def update
    authorize! :update, @shift

    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to shift_url(@shift), success: t("crud.controller.success.edited", name: Shift.model_name.human) }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1 or /shifts/1.json
  def destroy
    authorize! :destroy, @shift
    @shift.destroy

    respond_to do |format|
      format.html { redirect_to shifts_url, notice: t("crud.controller.success.deleted", name: Shift.model_name.human) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shift_params
      params.require(:shift).permit(:start_time, :end_time, :worker_id, :office_id)
    end
end

app/helpers/shifts_helper.rb
module ShiftsHelper

  def get_active_shifts(worker)
    Shift.where(worker: worker, end_time: nil)
  end

  def get_shifts_current_week(worker)
    start_time = DateTime.now.beginning_of_week
    end_time = DateTime.now.end_of_week
    Shift.where(worker: worker, start_time: start_time .. end_time).and(Shift.where.not(end_time: nil))
  end

  def sum_duration(shifts)
    shifts.to_a.sum(&:duration)
  end

end

app/views/shifts/_form.html.slim
= simple_form_for(@shift) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :start_time
    = f.input :end_time
    = f.association :worker
    = f.association :office

  .form-actions
    = f.button :submit, class: "btn-primary"

app/views/shifts/_shift.html.slim
div id="#{dom_id shift}"
  p
    strong Start time:
    =< shift.start_time
  p
    strong End time:
    =< shift.end_time
  p
    strong Worker:
    =< shift.worker_id
  p
    strong Office:
    =< shift.office_id

app/views/shifts/edit.html.slim
= page_heading t("shift.titles.edit_html", id: @shift.id)

== render "form", shift: @shift

br

div
  => link_to t("shift.links.view"), @shift
  '|
  =< link_to t("shift.links.back_list"), shifts_path

app/views/shifts/index.html.slim
= page_heading t("shift.titles.list")

- if can? :create, Shift
  h1
    a< class="text-black" href=new_shift_path
      i class="bi bi-plus-square-fill"

div class="table-responsive"
  table class="table table-striped table-sm records-table"
    thead class="table-dark"
      tr
        th
          a class=(@pager.sort_by == "id" ? "fst-italic" : "") href=shifts_path(sort_by: "id", sort_order: (@pager.sort_order == "asc" ? :desc : :asc))
            = t("id")
          - if @pager.sort_by == "id"
            - if @pager.sort_order == "asc"
              i<> class="bi bi-caret-up-fill"
            - else
              i<> class="bi bi-caret-down-fill"

        th = Shift.human_attribute_name :worker
        th = Shift.human_attribute_name :office
        th = Shift.human_attribute_name :office
        th
          a class=(@pager.sort_by == "start_time" ? "fst-italic" : "") href=shifts_path(sort_by: "start_time", sort_order: (@pager.sort_order == "asc" ? :desc : :asc))
            = Shift.human_attribute_name :start_time
          - if @pager.sort_by == "start_time"
            - if @pager.sort_order == "asc"
              i<> class="bi bi-caret-up-fill"
            - else
              i<> class="bi bi-caret-down-fill"
        th
          a class=(@pager.sort_by == "end_time" ? "fst-italic" : "") href=shifts_path(sort_by: "end_time", sort_order: (@pager.sort_order == "asc" ? :desc : :asc))
            = Shift.human_attribute_name :end_time
          - if @pager.sort_by == "end_time"
            - if @pager.sort_order == "asc"
              i<> class="bi bi-caret-up-fill"
            - else
              i<> class="bi bi-caret-down-fill"
        th = Shift.human_attribute_name :duration
        th = t("actions.actions")
    tbody class="table-group-divider"
      - @shifts.each do |shift|
        tr
          th = shift.id
          td
            a href=worker_path(shift.worker) = shift.worker.name
          td
            a href=office_path(shift.office) = shift.office.name
          td = l(shift.date, :format => :long)
          td = l(shift.start_time, :format => :long)
          td
            - if shift.end_time.present?
              = l(shift.end_time, :format => :long)
          td
            - if shift.end_time.present?
              = t("duration.minutes", minutes: shift.duration)
          td
            button type="button" class="btn btn-primary btn-sm me-2"
              a class="text-white" href=shift_path(shift)
                = t("actions.view")
                i class="bi bi-eye-fill ps-2"
            - if can? :update, shift
              button type="button" class="btn btn-primary btn-sm me-2"
                a class="text-white" href=admin_edit_shift_path(id: shift.id)
                  = t("actions.edit")
                  i class="bi bi-pencil-fill ps-2"
            - if can? :destroy, shift
              button type="button" class="btn btn-primary btn-sm me-2"
                a class="text-white" href=shift_path(shift) data-method="delete" data-confirm=t("actions.confirm")
                  = t("actions.delete")
                  i class="bi bi-trash-fill ps-2"

= pagination

app/views/shifts/new.html.slim
= page_heading t("shift.titles.create")

== render "form", shift: @shift

br

div
  = link_to t("shift.links.back_list"), shifts_path

app/views/shifts/show.html.slim
div class="container bg-light rounded-3 p-5 mb-4"
  div class="d-flex"
    div class="flex-grow-1 ms-3"
      = page_heading @shift.worker.name

      div class="row"
        div class="col-4"
          = Shift.human_attribute_name :office
        div class="col-8"
          = @shift.office.name

      div class="row"
        div class="col-4"
          = Office.human_attribute_name :full_address
        div class="col-8"
          = @shift.office.full_address

      div class="row"
        div class="col-4"
          = Shift.human_attribute_name :start_time
        div class="col-8"
          - if @shift.start_time.present?
            = l(@shift.start_time, :format => :long)

      div class="row"
        div class="col-4"
          = Shift.human_attribute_name :end_time
        div class="col-8"
          - if @shift.end_time.present?
            = l(@shift.end_time, :format => :long)

      div class="row"
        div class="col-4"
          = Shift.human_attribute_name :duration
        div class="col-8"
          - if @shift.end_time.present?
            = t("duration.minutes", minutes: @shift.duration)

    div class="flex-shrink-0"

  div class="container-fluid mt-3"
    div class="row"
      div class="col-12"
        - if can? :update, @shift
          button type="button" class="btn btn-dark btn-lg me-2"
            a class="text-white" href=admin_edit_shift_path(id: @shift.id)
              = t("actions.edit")
              i class="bi bi-pencil-fill ps-2"
        - if can? :destroy, @shift
          button type="button" class="btn btn-danger btn-lg me-2"
            a class="text-white" href=shift_path(@shift) data-method="delete" data-confirm=t("actions.confirm")
              = t("actions.delete")
              i class="bi bi-trash-fill ps-2"

  - if can? :update, @shift
    div class="container-fluid mt-3"
      = render "admin/shift_corrections/list"